---
# tasks file for roles/launch_front
- name: Launch Front
  docker_container:
    name: my-front
    image: albanlau/tp-devops-front
    ports:
      - "90:90"
    networks:
      - name: my_network
    state: started
    restart_policy: always