---
# tasks file for roles/launch_database
- name: Launch MySQL Database
  docker_container:
    name: my-db
    image: albanlau/tp-devops-database
    env:
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_DATABASE: "your_database"
      MYSQL_USER: "your_user"
      MYSQL_PASSWORD: "your_password"
    networks:
      - name: my_network
    state: started
    restart_policy: always
